site_name: db-ally
nav:
  - Home: index.md
  - Tutorials:
      - tutorials/index.md
      - tutorials/tutorial_1.md
  - Concepts:
      - concepts/concept_1.md
  - How-to:
      - how-to/quickstart.md
      - how-to/quickstart2.md
      - how-to/log_runs_to_langsmith.md
  - API Reference:
      - reference/collection.md
theme:
  name: material
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  mkdocstrings:
    handlers:
      python:
        options:
          extensions:
            - griffe_typingdoc
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
            - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true