site_name: db-ally
nav:
  - db-ally: index.md
  - Quickstart:
      - quickstart/index.md
      - quickstart/quickstart2.md
  - Tutorials:
      - tutorials.md
  - Concepts:
      - concepts/iql.md
      - concepts/views.md
      - concepts/collections.md
      - concepts/similarity_indexes.md
      - concepts/nl_responder.md
  - How-to:
      - how-to/log_runs_to_langsmith.md
      - how-to/create_custom_event_handler.md
      - how-to/implementing_similarity_index.md
      - how-to/sql_views.md
      - how-to/use_custom_llm.md
  - API Reference:
      - reference/collection.md
      - reference/event_handler.md
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - autorefs:
      enable: true
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true